using Soenneker.Gen.Adapt.Tests.Dtos;
using Soenneker.Tests.Unit;
using AwesomeAssertions;
using Soenneker.Enums.DayOfWeek;

namespace Soenneker.Gen.Adapt.Tests;

/// <summary>
/// Verifies that Soenneker.Gen.EnumValues and Soenneker.Gen.Adapt work together in the same project:
/// - Both source generators run and produce code without conflict.
/// - Adapt enum parsing (GenAdapt_EnumParsers) still works for C# enums.
/// - Adapt mappings work for DTOs that use EnumValue-generated types.
/// </summary>
[ClassDataSource<Host>(Shared = SharedType.PerTestSession)]
public sealed class EnumValuesIntegrationTests : UnitTest
{
    public EnumValuesIntegrationTests( output) : base(output)
    {
    }

    [Test]
    public void Both_Generators_Coexist_Adapt_Enum_Parsing_Works()
    {
        // GenAdapt_EnumParsers is generated by Soenneker.Gen.Adapt for C# enums.
        // If both generators conflict or build fails, this would not compile/run.
        var source = new StringToEnumSource { StatusString = "Active" };
        var result = source.Adapt<StringToEnumDest>();

        result.Should()
              .NotBeNull();
        result.StatusString.Should()
              .Be(TestStatus.Active);
    }

    [Test]
    public void Both_Generators_Coexist_EnumValues_FromValue_Works()
    {
        // TestOrderStatus.FromValue is generated by Soenneker.Gen.EnumValues.
        // Proves EnumValues generator ran and generated API is available.
        TestOrderStatus status = TestOrderStatus.FromValue(1);
        status.Should()
              .Be(TestOrderStatus.Pending);
        status.Value.Should()
              .Be(1);
    }

    [Test]
    public void Adapt_Maps_EnumValue_Type_Same_Type()
    {
        // Adapt maps DTOs where the property type is an EnumValue-generated type (same type on both sides).
        var source = new EnumValueTypeSource { Status = TestOrderStatus.Completed };

        var result = source.Adapt<EnumValueTypeDest>();

        result.Should()
              .NotBeNull();
        result.Status.Should()
              .Be(TestOrderStatus.Completed);
        result.Status.Value.Should()
              .Be(2);
    }

    [Test]
    public void Adapt_Maps_EnumValue_Type_Pending()
    {
        var source = new EnumValueTypeSource { Status = TestOrderStatus.Pending };

        var result = source.Adapt<EnumValueTypeDest>();

        result.Should()
              .NotBeNull();
        result.Status.Should()
              .Be(TestOrderStatus.Pending);
    }

    [Test]
    public void EnumValues_List_And_Adapt_Work_Together()
    {
        // Use EnumValues-generated List to iterate, then use one value in an Adapt mapping.
        foreach (TestOrderStatus status in TestOrderStatus.List)
        {
            var source = new EnumValueTypeSource { Status = status };
            var result = source.Adapt<EnumValueTypeDest>();
            result.Status.Should()
                  .Be(status);
        }
    }

    [Test]
    public void CSharp_Enum_And_EnumValue_Type_Both_Used_In_Same_Project()
    {
        // C# enum (TestStatus) -> Adapt generates Parse_TestStatus; EnumValue type (TestOrderStatus) -> EnumValues generates List/FromValue.
        var enumSource = new EnumSource { Status = TestStatus.Completed, Priority = 1 };
        var enumDest = enumSource.Adapt<EnumToStringDest>();
        enumDest.Status.Should()
                .Be("Completed");

        var orderSource = new EnumValueTypeSource { Status = TestOrderStatus.FromValue(2) };
        var orderDest = orderSource.Adapt<EnumValueTypeDest>();
        orderDest.Status.Should()
                 .Be(TestOrderStatus.Completed);
    }

    // --- EnumValue<string> (TestColorCode) ---

    [Test]
    public void EnumValue_String_FromValue_Works()
    {
        TestColorCode color = TestColorCode.FromValue("R");
        color.Should()
             .Be(TestColorCode.Red);
        color.Value.Should()
             .Be("R");
    }

    [Test]
    public void EnumValue_String_FromName_Works()
    {
        TestColorCode color = TestColorCode.FromName("Blue");
        color.Should()
             .Be(TestColorCode.Blue);
        color.Value.Should()
             .Be("B");
    }

    [Test]
    public void Adapt_Maps_EnumValue_String_Type_Same_Type()
    {
        var source = new EnumValueStringTypeSource { Color = TestColorCode.Green };

        var result = source.Adapt<EnumValueStringTypeDest>();

        result.Should()
              .NotBeNull();
        result.Color.Should()
              .Be(TestColorCode.Green);
        result.Color.Value.Should()
              .Be("G");
    }

    [Test]
    public void EnumValue_String_List_And_Adapt_Work_Together()
    {
        foreach (TestColorCode color in TestColorCode.List)
        {
            var source = new EnumValueStringTypeSource { Color = color };
            var result = source.Adapt<EnumValueStringTypeDest>();
            result.Color.Should()
                  .Be(color);
        }
    }

    // --- Same-type: identity vs copy (HasAccessibleParameterlessConstructor) ---

    [Test]
    public void Adapt_EnumValue_same_type_returns_same_reference_TestOrderStatus()
    {
        // EnumValue types have no public parameterless ctor → generator emits "return source" (identity).
        var source = new EnumValueTypeSource { Status = TestOrderStatus.Completed };
        var result = source.Adapt<EnumValueTypeDest>();

        result.Status.Should().BeSameAs(source.Status);
        result.Status.Should().Be(TestOrderStatus.Completed);
    }

    [Test]
    public void Adapt_EnumValue_same_type_returns_same_reference_TestColorCode()
    {
        // EnumValue<string> same behavior: identity when same-type mapping.
        var source = new EnumValueStringTypeSource { Color = TestColorCode.Green };
        var result = source.Adapt<EnumValueStringTypeDest>();

        result.Color.Should().BeSameAs(source.Color);
        result.Color.Should().Be(TestColorCode.Green);
    }

    [Test]
    public void Adapt_DayOfWeekType_same_type_returns_same_reference()
    {
        // DayOfWeekType (EnumValue<string>) must use identity, not "new DayOfWeekType()".
        DayOfWeekType source = DayOfWeekType.Wednesday;
        var result = source.Adapt<DayOfWeekType>();

        result.Should().BeSameAs(source);
        result.Should().Be(DayOfWeekType.Wednesday);
    }

    [Test]
    public void Adapt_DayOfWeekType_via_DTO_returns_same_reference()
    {
        var source = new DayOfWeekTypeSource { Day = DayOfWeekType.Friday };
        var result = source.Adapt<DayOfWeekTypeDest>();

        result.Day.Should().BeSameAs(source.Day);
        result.Day.Should().Be(DayOfWeekType.Friday);
    }

    // --- Same-assembly EnumValues (types defined in this test project, Adapt called here) ---

    [Test]
    public void SameAssembly_EnumValue_int_TestOrderStatus_Adapt_root_returns_identity()
    {
        // TestOrderStatus is [EnumValue] (int) in this assembly; Adapt<T>() at root must return same reference.
        TestOrderStatus source = TestOrderStatus.Completed;
        var result = source.Adapt<TestOrderStatus>();

        result.Should().BeSameAs(source);
        result.Value.Should().Be(2);
    }

    [Test]
    public void SameAssembly_EnumValue_int_TestOrderStatus_Adapt_via_DTO_returns_identity()
    {
        // TestOrderStatus in this assembly; mapping DTOs that hold it must preserve reference.
        var source = new EnumValueTypeSource { Status = TestOrderStatus.Pending };
        var result = source.Adapt<EnumValueTypeDest>();

        result.Status.Should().BeSameAs(source.Status);
        result.Status.Should().Be(TestOrderStatus.Pending);
    }

    [Test]
    public void SameAssembly_EnumValue_string_TestColorCode_Adapt_root_returns_identity()
    {
        // TestColorCode is [EnumValue<string>] in this assembly; Adapt<T>() at root must return same reference.
        TestColorCode source = TestColorCode.Green;
        var result = source.Adapt<TestColorCode>();

        result.Should().BeSameAs(source);
        result.Value.Should().Be("G");
    }

    [Test]
    public void SameAssembly_EnumValue_string_TestColorCode_Adapt_via_DTO_returns_identity()
    {
        // TestColorCode in this assembly; mapping DTOs that hold it must preserve reference.
        var source = new EnumValueStringTypeSource { Color = TestColorCode.Red };
        var result = source.Adapt<EnumValueStringTypeDest>();

        result.Color.Should().BeSameAs(source.Color);
        result.Color.Should().Be(TestColorCode.Red);
    }

    [Test]
    public void SameAssembly_All_EnumValue_types_roundtrip_via_Adapt()
    {
        // Same-assembly EnumValue types only (TestOrderStatus, TestColorCode defined in this test project).
        TestOrderStatus order = TestOrderStatus.FromValue(1);
        order.Adapt<TestOrderStatus>().Should().BeSameAs(order);

        TestColorCode color = TestColorCode.FromName("Blue");
        color.Adapt<TestColorCode>().Should().BeSameAs(color);

        new EnumValueTypeSource { Status = order }.Adapt<EnumValueTypeDest>().Status.Should().BeSameAs(order);
        new EnumValueStringTypeSource { Color = color }.Adapt<EnumValueStringTypeDest>().Color.Should().BeSameAs(color);
    }

    [Test]
    public void Adapt_type_with_parameterless_ctor_same_type_returns_new_instance()
    {
        // When mapping T -> T at the root (item.Adapt<CopyableItem>()), types with accessible parameterless ctor get "new T()" and copy.
        var source = new CopyableItem { Id = 42, Name = "foo" };
        var result = source.Adapt<CopyableItem>();

        result.Should().NotBeSameAs(source);
        result.Id.Should().Be(42);
        result.Name.Should().Be("foo");
    }
}