using System.Text;

namespace Soenneker.Gen.Adapt;

internal static class Collections
{
    public static void Emit(StringBuilder sb, string targetNamespace)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(targetNamespace);
        sb.AppendLine("{");
        sb.AppendLine("\tpublic static partial class GenAdapt_Collections");
        sb.AppendLine("\t{");
        // List<T> -> clone
        sb.AppendLine("\t\t[GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static List<TElement> Adapt<TElement>(this List<TElement> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar result = new List<TElement>(source.Count);");
        sb.AppendLine("\t\t\tfor (int i = 0; i < source.Count; i++) result.Add(source[i]);");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // IEnumerable<T> -> materialize (stable behavior)
        sb.AppendLine("\t\t[GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static IEnumerable<TElement> Adapt<TElement>(this IEnumerable<TElement> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar list = new List<TElement>();");
        sb.AppendLine("\t\t\tforeach (var item in source) list.Add(item);");
        sb.AppendLine("\t\t\treturn list;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // Dictionary<TKey,TValue>
        sb.AppendLine("\t\t[GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static Dictionary<TKey, TValue> Adapt<TKey, TValue>(this Dictionary<TKey, TValue> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tif (source.Count == 0) return new Dictionary<TKey, TValue>();");
        sb.AppendLine("\t\t\tvar result = new Dictionary<TKey, TValue>(source.Count);");
        sb.AppendLine("\t\t\tforeach (var kv in source) result[kv.Key] = kv.Value;");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // IDictionary<TKey,TValue>
        sb.AppendLine("\t\t[GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static IDictionary<TKey, TValue> Adapt<TKey, TValue>(this IDictionary<TKey, TValue> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar result = new Dictionary<TKey, TValue>(source.Count);");
        sb.AppendLine("\t\t\tforeach (var kv in source) result[kv.Key] = kv.Value;");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // IReadOnlyDictionary<TKey,TValue>
        sb.AppendLine("\t\t[GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static IReadOnlyDictionary<TKey, TValue> Adapt<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar result = new Dictionary<TKey, TValue>(source.Count);");
        sb.AppendLine("\t\t\tforeach (var kv in source) result[kv.Key] = kv.Value;");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // IReadOnlyList<T>
        sb.AppendLine("\t\t[GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static IReadOnlyList<TElement> Adapt<TElement>(this IReadOnlyList<TElement> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar result = new List<TElement>(source.Count);");
        sb.AppendLine("\t\t\tfor (int i = 0; i < source.Count; i++) result.Add(source[i]);");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // IReadOnlyCollection<T>
        sb.AppendLine("\t\t[GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static IReadOnlyCollection<TElement> Adapt<TElement>(this IReadOnlyCollection<TElement> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar result = new List<TElement>(source.Count);");
        sb.AppendLine("\t\t\tforeach (var item in source) result.Add(item);");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // Array<T>
        sb.AppendLine("\t\t[GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static TElement[] Adapt<TElement>(this TElement[] source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar result = new TElement[source.Length];");
        sb.AppendLine("\t\t\tArray.Copy(source, result, source.Length);");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // IList<T>
        sb.AppendLine("\t\t[System.CodeDom.Compiler.GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static IList<TElement> Adapt<TElement>(this IList<TElement> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar result = new List<TElement>(source.Count);");
        sb.AppendLine("\t\t\tfor (int i = 0; i < source.Count; i++) result.Add(source[i]);");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // ICollection<T>
        sb.AppendLine("\t\t[System.CodeDom.Compiler.GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static ICollection<TElement> Adapt<TElement>(this ICollection<TElement> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\tvar result = new List<TElement>(source.Count);");
        sb.AppendLine("\t\t\tforeach (var item in source) result.Add(item);");
        sb.AppendLine("\t\t\treturn result;");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // HashSet<T>
        sb.AppendLine("\t\t[System.CodeDom.Compiler.GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static HashSet<TElement> Adapt<TElement>(this HashSet<TElement> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\treturn new HashSet<TElement>(source);");
        sb.AppendLine("\t\t}");
        sb.AppendLine();

        // ISet<T>
        sb.AppendLine("\t\t[System.CodeDom.Compiler.GeneratedCode(\"Soenneker.Gen.Adapt\", \"3.0.0\")] ");
        sb.AppendLine("\t\t[ExcludeFromCodeCoverage]");
        sb.AppendLine("\t\tpublic static ISet<TElement> Adapt<TElement>(this ISet<TElement> source)");
        sb.AppendLine("\t\t{");
        sb.AppendLine("\t\t\tif (source is null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine("\t\t\treturn new HashSet<TElement>(source);");
        sb.AppendLine("\t\t}");
        sb.AppendLine("\t}");
        sb.AppendLine("}");
    }
}
